### ISSUE TITLE
Html element not work as expect with View

### ISSUE THREAD

**Issue by Zipexpo** [pmndrs/drei#893] opened 2022-05-08 19:32 UTC
- `three` version: 0.139.2
- `@react-three/fiber` version: 8.0.12
- `@react-three/drei` version: 9.7.1
- `npm` (or `yarn`) version: 6.14.13

### Problem description:

despite Html tag in different view, it always appear on the first View. In the example below, I put Html on the View3 but it appear on the view 1. I even use portal option to view3 but not worked.
https://codesandbox.io/s/view-skissor-forked-x18lig 

### Relevant code:

```js
<View index={3} track={view3}>
          <color attach="background" args={['#bbfeeb']} />
          <PerspectiveCamera makeDefault position={[0, 0, 4]} />
          <Lights preset="dawn" />
          <Soda scale={3} position={[0, -0.75, 0]} />
          <OrbitControls makeDefault />
          <Html transform portal={view3}>
            <div>I have something to say</div>
          </Html>
          <CameraShake intensity={2} />
        </View>
```

### Suggested solution:

Perhaps, is it related to the position feature of Html component??

**Comment by FarazzShaikh** [comment] 2022-06-12 20:18
This is expected since <Html /> has `position: 'aboslute'`, you need to have the `portal` prop be a `position: 'relative'` element. [Working demo here](https://codesandbox.io/s/view-skissor-forked-8t27to?file=/src/App.js:1729-1735)

I presume this would be "broken" outside of `<View />` too if you use an element outide the canvas as the `portal` element. 

Closing as not a bug.

**Closed by FarazzShaikh** 2022-06-12 20:18 UTC
Labels: bug
