### ISSUE TITLE
SyntaxError: Unexpected token 'export' for mediapipe/tasks-vision/vision_bundle.js

### ISSUE THREAD

**Issue by antonsjolander** [pmndrs/drei#1499] opened 2023-06-07 09:24 UTC
- `three` version:
- `@react-three/fiber` version: 9.7.2
- `@react-three/drei` version: 9.74.6
- `node` version: 18.12.0
- `npm` (or `yarn`) version: 8.19.2

### Problem description:

I get this issue when i try to build or run dev in my NEXT.js project 

Server Error
SyntaxError: Unexpected token 'export'

```
This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
<unknown>
/Users/antonstrandqvist/dev/sites/n4xt/n4xt-frontend/node_modules/ (mediapipe/tasks-vision/vision_bundle.js (1)
Object.compileFunction
node:vm (360:18)
wrapSafe
node:internal/modules/cjs/loader (1088:15)
Module._compile
node:internal/modules/cjs/loader (1123:27)
Module._extensions..js
node:internal/modules/cjs/loader (1213:10)
Module.load
node:internal/modules/cjs/loader (1037:32)
Module._load
node:internal/modules/cjs/loader (878:12)
Module.require
node:internal/modules/cjs/loader (1061:19)
require
node:internal/modules/cjs/helpers (103:18)
Object.<anonymous>
file:///Users/antonstrandqvist/dev/sites/n4xt/n4xt-frontend/node_modules/@react-three/drei/index.cjs.js (1:600)
Module._compile
node:internal/modules/cjs/loader (1159:14)
Module._extensions..js
node:internal/modules/cjs/loader (1213:10)
Module.load
node:internal/modules/cjs/loader (1037:32)
Module._load
node:internal/modules/cjs/loader (878:12)
Module.require
node:internal/modules/cjs/loader (1061:19)
require
node:internal/modules/cjs/helpers (103:18)
@react-three/drei
file:///Users/antonstrandqvist/dev/sites/n4xt/n4xt-frontend/.next/server/pages/index.js (392:18)
__webpack_require__
file:///Users/antonstrandqvist/dev/sites/n4xt/n4xt-frontend/.next/server/webpack-runtime.js (33:42)
eval
webpack-internal:///./src/components/dom/Loaders/main.tsx (12:75)
__webpack_require__.a
file:///Users/antonstrandqvist/dev/sites/n4xt/n4xt-frontend/.next/server/webpack-runtime.js (97:13)
eval
webpack-internal:///./src/components/dom/Loaders/main.tsx (1:21)
./src/components/dom/Loaders/main.tsx
file:///Users/antonstrandqvist/dev/sites/n4xt/n4xt-frontend/.next/server/pages/index.js (263:1)
__webpack_require__
file:///Users/antonstrandqvist/dev/sites/n4xt/n4xt-frontend/.next/server/webpack-runtime.js (33:42)
eval
webpack-internal:///./src/pages/index.tsx (15:86)
__webpack_require__.a
file:///Users/antonstrandqvist/dev/sites/n4xt/n4xt-frontend/.next/server/webpack-runtime.js (97:13)
eval
webpack-internal:///./src/pages/index.tsx (1:21)
./src/pages/index.tsx
file:///Users/antonstrandqvist/dev/sites/n4xt/n4xt-frontend/.next/server/pages/index.js (329:1)
__webpack_require__
file:///Users/antonstrandqvist/dev/sites/n4xt/n4xt-frontend/.next/server/webpack-runtime.js (33:42)
eval
webpack-internal:///./node_modules/next/dist/build/webpack/loaders/next-route-loader.js (6:78)
__webpack_require__.a
file:///Users/antonstrandqvist/dev/sites/n4xt/n4xt-frontend/.next/server/webpack-runtime.js (97:13)
eval
webpack-internal:///./node_modules/next/dist/build/webpack/loaders/next-route-loader.js (1:21)
./node_modules/next/dist/build/webpack/loaders/next-route-loader.js?page=%2F&absolutePagePath=.%2Fsrc%2Fpages%2Findex.tsx&preferredRegion=!
file:///Users/antonstrandqvist/dev/sites/n4xt/n4xt-frontend/.next/server/pages/index.js (32:1)
__webpack_require__
file:///Users/antonstrandqvist/dev/sites/n4xt/n4xt-frontend/.next/server/webpack-runtime.js (33:42)
__webpack_exec__
file:///Users/antonstrandqvist/dev/sites/n4xt/n4xt-frontend/.next/server/pages/index.js (776:39)
<unknown>
file:///Users/antonstrandqvist/dev/sites/n4xt/n4xt-frontend/.next/server/pages/index.js (777:28)
Object.<anonymous>
file:///Users/antonstrandqvist/dev/sites/n4xt/n4xt-frontend/.next/server/pages/index.js (780:3)
Module._compile
node:internal/modules/cjs/loader (1159:14)
Module._extensions..js
node:internal/modules/cjs/loader (1213:10)
Module.load
node:internal/modules/cjs/loader (1037:32)
Module._load
node:internal/modules/cjs/loader (878:12)
Module.require
node:internal/modules/cjs/loader (1061:19)
require
node:internal/modules/cjs/helpers (103:18)
requirePage
file:///Users/antonstrandqvist/dev/sites/n4xt/n4xt-frontend/node_modules/next/dist/server/require.js (156:12)
<unknown>
file:///Users/antonstrandqvist/dev/sites/n4xt/n4xt-frontend/node_modules/next/dist/server/load-components.js (68:84)
process.processTicksAndRejections
node:internal/process/task_queues (95:5)
async loadComponentsImpl
file:///Users/antonstrandqvist/dev/sites/n4xt/n4xt-frontend/node_modules/next/dist/server/load-components.js (68:26)
async DevServer.findPageComponentsImpl
file:///Users/antonstrandqvist/dev/sites/n4xt/n4xt-frontend/node_modules/next/dist/server/next-server.js (762:36)
async DevServer.findPageComponents
file:///Users/antonstrandqvist/dev/sites/n4xt/n4xt-frontend/node_modules/next/dist/server/dev/next-dev-server.js (1297:20)
async DevServer.renderPageComponent
file:///Users/antonstrandqvist/dev/sites/n4xt/n4xt-frontend/node_modules/next/dist/server/base-server.js (1301:24)
async DevServer.renderToResponseImpl
file:///Users/antonstrandqvist/dev/sites/n4xt/n4xt-frontend/node_modules/next/dist/server/base-server.js (1344:32)
async DevServer.pipeImpl
file:///Users/antonstrandqvist/dev/sites/n4xt/n4xt-frontend/node_modules/next/dist/server/base-server.js (628:25)
```

this seem to be an issue with drei

**Comment by onmyway133** [comment] 2023-06-07 13:35
This seems to be related to mediapipe https://github.com/google/mediapipe/issues/4398

**Comment by sharanda** [comment] 2023-06-12 13:38
I've experienced the same issue after I tried to upgrade my project.
Indeed, seems to be related to the mediapipe dependecy that appeared in the yarn.lock
Couldn't find any soluting and had to revert the upgrade.
![image](https://github.com/pmndrs/drei/assets/32507483/f6b001b4-7783-432e-abfd-e3292917166b)

**Comment by gsimone** [comment] 2023-06-12 16:09
Duplicate of #1500

**Closed by gsimone** 2023-06-12 16:09 UTC
Labels: bug
