### ISSUE TITLE
Overflow: hidden style added to the root div of Html elements with transform enabled causes rendering issues on Firefox 

### ISSUE THREAD

**Issue by cirzoltan** [pmndrs/drei#507] opened 2021-08-05 10:36 UTC
- `three` version: 0.131.2
- `@react-three/fiber` version: 7.0.6
- `@react-three/drei` version: 7.2.2
- `node` version: 14.17.0
- `npm` (or `yarn`) version: 7.19.0

### Problem description:

There's an `overflow: hidden` style added to the root div of `<Html>` element with `transform={true}` which causes rendering glitches (z fighting?) in Firefox (90.0.2).

### Suggested solution:
Adding a `overflow: unset !important;` css rule to overwrite the `overflow: hidden` style on the root div fixes the issue and does not seem to otherwise affect behavior.

**Comment by joshuaellis** [comment] 2021-08-05 10:40
Please provide a code reproduction so we can look at the issue.

**Comment by cirzoltan** [comment] 2021-08-05 10:53
https://codesandbox.io/embed/currying-moon-q360u?fontsize=14&hidenavigation=1&theme=dark

1. Open on Chrome
2. Open on Firefox
3. Compare
4. Optional: Try resizing the Firefox window

**Comment by cirzoltan** [comment] 2021-08-05 10:56
To try the workaround uncomment the css rule related to #fixme in styles.css

**Comment by njm222** [comment] 2021-08-06 07:22
Here is the commit when it was added: https://github.com/pmndrs/drei/commit/be9ae6966b54ccac4f6c0b3a0f29d32e61ed79c7#diff-eb7dcf4ddfc3cb0afb087ecbfb9543791f4153b544af8c5081da23c29e4a2a6bR121

I'm not sure why pointerEvents & overflow are needed here...
@GiuseppeRaso said he was just copying the three.js implementation here: 
https://github.com/mrdoob/three.js/blob/38954eff2bcac74895fb0e7914ae33e9998fd0c5/examples/js/renderers/CSS3DRenderer.js

The origin of the `overflow: hidden` is this commit from doob: https://github.com/mrdoob/three.js/commit/e570e88cdb7fdad8c958e9cf28853b9720c2486e#diff-1339c04e8c99a18fae1019124b65558d8781ec3b8faa9d8e5f82f4325cf53826

which appears to fix an IOS edge case, so it may not be needed anymore

**Comment by njm222** [comment] 2021-08-06 07:27
I personally would like to remove both the pointerEvents & overflow styles and just leave it up to the user to add styles to the main & inner divs

**Comment by cirzoltan** [comment] 2021-08-06 08:53
Being able to style the root div directly would definitely be nice. I noticed that styles specified on the element are actually passed on to the root div when transform is false but not when transform is true. (look around line 164 in `Html.tsx`)

**Comment by njm222** [comment] 2021-08-06 10:27
yes they are but I propose that the styles also get passed when transform is true so we can remove the _opinionated_ styles (pointerEvents & overflow)

**Comment by joshuaellis** [comment] 2021-08-09 15:38
I think it's probably helpful to remove unopinionated styles yes... Maybe we should be passing a `styles` object, if it goes to the same element 🤔

**Comment by njm222** [comment] 2021-08-16 08:41
yes passing an additional `styles` object to the parent is an option, but I think it's starting to make things convoluted & tangled since the new style prop we are going to add will only be applicable when transform = true

Currently we have two _main versions_ of the html component.. transform = true / false

I think when transform = false the component is fine as the user has full control of it.

However when transform = true there are opinionated styles on the parent element `el` https://github.com/pmndrs/drei/blob/master/src/web/Html.tsx#L147

Thoughts:
`overflow:hidden;` could be removed, but I do not know all the implications of the change
`pointer-events:none;` is fine to stay if we make pointerEvents an optional prop for the innerDiv (https://github.com/pmndrs/drei/blob/master/src/web/Html.tsx#L191)

**Comment by joshuaellis** [comment] 2021-09-19 10:41
I believe this was resolved in #492

**Closed by joshuaellis** 2021-09-19 10:41 UTC
Labels: bug
