### ISSUE TITLE
Preventing onClick event when panning with MapControls

### ISSUE THREAD

**Issue by dumaron** [pmndrs/drei#41] opened 2020-06-17 07:58 UTC
I'm trying to move a 2d plane with clickable objects. 
Everything works fine with `MapControls`, but if I start panning when the cursor is over an object a click event is triggered when the mouse is released.

[Here's a sandbox](https://codesandbox.io/s/react-three-fiber-map-0s5e8?file=/src/index.js) to show the problem. The black objects are clickable: try to move the map starting from one of them and watch the console.

Do you think it's possible to prevent the click event from firing up if the camera has moved?

**Comment by giulioz** [comment] 2020-06-17 08:07
I've had the same problem in another project, I ended up rewriting MapControls using [react-use-gesture](https://github.com/react-spring/react-use-gesture).

The key idea is to begin a pan only if the movement exceeds a delta, and stop the event bubbling if panning has started:

```typescript
const bind = useGesture(
    {
      onDrag: ({ last, delta, movement, event }) => {
        const deltaXR =
          delta[0] * movementXVector.current.x +
          delta[1] * -movementXVector.current.z;
        const deltaYR =
          delta[0] * movementYVector.current.x +
          delta[1] * -movementYVector.current.z;

        // debounce for click events that moves camera
        // (item select)
        const d = movement[0] ** 2 + movement[1] ** 2;
        if (d > 80) {
          const distance = camStateAnim.distance.get();
          const targetX =
            camStateAnim.targetX.get() +
            deltaXR *
              (distance / moveSpeedDistanceFactor) *
              moveSpeedDrag *
              (fromTop ? fromTopSpeed : 1);
          const targetY = camStateAnim.targetY.get();
          const targetZ =
            camStateAnim.targetZ.get() +
            deltaYR *
              (distance / moveSpeedDistanceFactor) *
              moveSpeedDrag *
              (fromTop ? fromTopSpeed : 1);

          setCamStateAnim({ targetX, targetZ, immediate: true });

          if (last) {
            onZoom(distance);
            onMove([targetX, targetY, targetZ]);
          }

          event.stopPropagation();
          event.preventDefault();
          return false;
        }
      },
   }
);
```

**Comment by gsimone** [comment] 2020-06-17 08:44
This could probably be a good thing to add to Drei

**Comment by drcmda** [comment] 2020-06-17 09:12
the thing is that it's still expected behaviour, for instance try it with a dom element. the "Write / Preview" tabs here on github for instance. you can click, move, release and as long as it's the same target click will fire. r3f emulates that. 

one way to circumvent it could be to switch off canvas events while controls are active: https://codesandbox.io/s/react-three-fiber-map-pm6m6

> This could probably be a good thing to add to Drei

these usegesture controls are super interesting and lean. this is the second one i saw. first one is here: https://github.com/youroff/planet_disco/blob/master/assets/js/planet_disco/common/controls/tilted.jsx

i would love to have controls in that form, but must be:

1. stable
2. support touch & mobile
3. lerp instead of spring (faster i guess and you most likely dont need wobbly controls)
4. allow programmatic steering: `controls.ref.pan(x, y); ...zoom(...); ...etc`

**Comment by giulioz** [comment] 2020-06-17 09:35
I'm fixing my implementation and posting it as pull request.
Are you sure about programmatic steering? Wouldn't be better getting pan/zoom from props?

**Comment by youroff** [comment] 2020-06-17 10:01
This is what I did to tell `click` from `move/drag`:
https://github.com/youroff/planet_disco/blob/master/assets/js/planet_disco/genres_view/genre_cloud.jsx#L15-L43

It looks a bit ugly, but it works. However I'd love to see more general solution at the higher level.

**Comment by giulioz** [comment] 2020-06-17 11:19
@dumaron is this helpful?

https://codesandbox.io/s/r3f-scrollcontrols-kt4ey

**Comment by dumaron** [comment] 2020-06-17 13:03
Thanks, @giulioz ! While this example is helpful and it achieves my goal, I've some doubts about it.

By using the `clickDisabled` prop derived from `scrollProps.dragging`, it needs explicit handling of the click/pan aspect. This way of structuring the code is effective but might be tedious if the click handlers are nested under many levels of components. It's possible to use a context (that may even pair well with the `ScrollControls` component), but contexts have their own complexities.

I think I'll stick with your code but, in the meantime, I'll try to find a solution where the dragging event is able to prevent the `onClick` execution in a more implicit way. Maybe other developers, tomorrow, can decide to prevent the click events just by setting a prop on `MapControls` - or our new implementation of it based on `react-use-gesture`.

@drcmda I've read your opinion about this behavior previously (maybe was an issue on r3f, I can't remember) and I get your point, but I'm not super-convinced about that. While you're right about the "same target" concept, I don't think that this is a common approach when you're dealing with dragging or panning things around. 
Maybe I can give a look at some drag'n'drop libraries to see if they use this approach even in their case.

Anyway, since everything is working as expected, that's not really an issue. I'm completely satisfied with the discussion so you can close if you think that's better.

**Comment by giulioz** [comment] 2020-06-17 13:10
A better way to handle it may be to globally disable click events on r3f raycaster with `scrollProps.dragging`, instead of handling disable separately for every handler 🤔

**Comment by drcmda** [comment] 2020-06-17 16:03
@giulioz that would be great, i guess orbit and trackball and the two most used. if we had that in useGesture form with some way to drive it by code or props, that would be a huge step!

as for props, the problem is that it will go out of sync. this is why react for instance doesn't have a scrollOffset prop - it makes little sense because interaction changes state. image you set zoom={10} and it lerps there. now the user zooms back out again and your code says, again, "zoom=10", react will discard that prop.

**Comment by drcmda** [comment] 2020-06-17 16:15
> . While you're right about the "same target" concept, I don't think that this is a common approach when you're dealing with dragging or panning things around.

the thing is, if you had a drag going on an element, i dont think there would be a click, and if so it would probably a bug. but youre using another event source, orbit uses window events. so im almost 99% sure you would run into the same issue if you wanted that behaviour with the dom.

if there's a solution that's not specific to a single usecase and that isn't hacky - i would merge it.

**Comment by neftaly** [comment] 2020-06-19 01:52
I had a similar problem, and have been working on a different system for camera/gesture handling. I pulled some code out in case it helps someone in the meantime: https://github.com/probability-nz/r3f-gesture-example

You can see this approach in use [here](https://beta.probability.nz), though it's only really meant to be used with a multitouch screen at the moment.

**Comment by joshuaellis** [comment] 2021-01-14 18:27
I'm going to close this as there hasn't really been any activity, but if anyone has a proposal that (and I quote drcmda)

>not specific to a single usecase and that isn't hacky

We can reopen and revisit.

**Closed by joshuaellis** 2021-01-14 18:27 UTC
