### ISSUE TITLE
Orthographic Camera Unexpected Change on Scroll and Zoom

### ISSUE THREAD

**Issue by DavidNaumann** [pmndrs/drei#548] opened 2021-09-20 13:19 UTC
- `three` version: 0.131.3
- `@react-three/fiber` version: 6.0.13 
- `@react-three/drei` version: 7.5.0
- `node` version: v14.17.5
- `npm` (or `yarn`) version: 6.14.14

### Problem description: 

The orthographic camera has an unexpected change on zoom and scroll where the entire scene zooms out where the object that was focused on is a dot in the distance. This would make sense if the change of the viewport was the issue however the perspective camera doesn't have this issue.

### Relevant code:

```js
<drei.OrthographicCamera ref={cam} makeDefault position={[0, 0, 4]} right={2.5} left={-2.5} bottom={-2.5} top={2.5} zoom={3} />
```

### Suggested solution: 

I would expect that maybe the solution would come possibly in by looking at the differences between how the perspective camera is laid out and how the orthographic camera is laid out. Because the perspective camera has the expected result as compared to the orthographic camera.

### Pictures:
Orthographic Unzoomed:
![orthographic_unzoomed](https://user-images.githubusercontent.com/7818467/134009160-13bd577f-eff6-42b7-883e-1377d7fdeeb7.PNG)
Orthographic Zoomed:
![orthographic_zoomed](https://user-images.githubusercontent.com/7818467/134009161-d41d8474-52ab-48cc-8f73-69045350f232.PNG)

Perspective Unzoomed:
![perspective_unzoomed](https://user-images.githubusercontent.com/7818467/134009162-9643e808-39e8-443d-ad90-e287231a2a22.PNG)
Perspective Zoomed:
![perspective_zoomed](https://user-images.githubusercontent.com/7818467/134009163-f4b756c0-6e9b-4a2d-a95c-b3b64c2d1707.PNG)

**Comment by joshuaellis** [comment] 2021-09-20 19:15
Please provide a small reproduction of the issue, perhaps a code sandbox! 😄

**Comment by DavidNaumann** [comment] 2021-09-20 20:01
Provided example: https://codesandbox.io/s/romantic-snow-esvty?file=/src/App.js

**Comment by DavidNaumann** [comment] 2021-09-20 20:08
Code recreation for easy view outside of the codesandbox:

```js
import "./styles.css";
import { useRef } from "react";
import { Canvas } from "@react-three/fiber";
import { Vector3 } from "three";

const drei = require("@react-three/drei");

export default function App() {
  const cam = useRef();
  const position = new Vector3(0, 0, 0);

  return (
    <Canvas>
      <drei.OrthographicCamera
        ref={cam}
        makeDefault
        position={[0, 0, 4]}
        right={2.5}
        left={-2.5}
        bottom={-2.5}
        top={2.5}
        zoom={3}
      />
      <ambientLight />
      <drei.Box args={[1, 1, 1]} position={position}>
        <meshStandardMaterial attach="material" color="red" />
      </drei.Box>
    </Canvas>
  );
}
```

**Comment by looeee** [comment] 2021-09-23 13:18
I think this is a duplicate of #515

**Comment by joshuaellis** [comment] 2021-09-24 07:20
I think you're right. Closing in favour of #515

**Closed by joshuaellis** 2021-09-24 07:20 UTC
Labels: bug

**Comment by looeee** [comment] 2021-09-24 07:42
@DavidNaumann nonetheless thanks for the report and test sandbox. It'll make solving #515 easier 👍
