### ISSUE TITLE
TransformControls axes lose color/get invisible after hovering

### ISSUE THREAD

**Issue by asfg84** [pmndrs/drei#410] opened 2021-05-24 19:11 UTC
I upgraded to the latest version of drei (5.2.0) and found that the TransformControls lose their color after first hovering. I would expect the TransformControls to show the red-green-blue-colored axes when not hovering a single axis, but it's all white and only the axis I hovered last is visible. This behavior is also in the storybook (https://drei.pmnd.rs/?path=/story/controls-transformcontrols--transform-controls-story), but I don't think this behavior is intended, since it is also not like that in plain three.

I am using 
"@react-three/drei": "^5.2.0",
"@react-three/fiber": "^6.2.1",
"three": "0.128.0"

**Comment by joshuaellis** [comment] 2021-05-25 07:29
I think this is a duplicate of https://github.com/pmndrs/three-stdlib/issues/60 which was previously an issue here in `drei` but I moved to `three-stdlib`. Probably best to keep this open as a reference so people don't keep reporting it though 😅

**Comment by joshuaellis** [comment] 2021-06-10 21:57
solved by https://github.com/pmndrs/three-stdlib/pull/64

**Closed by joshuaellis** 2021-06-10 21:57 UTC
Labels: bug, three-stdlib
