### ISSUE TITLE
Unable to import anything after installing the package, I get the following import error

### ISSUE THREAD

**Issue by anuragnandi** [pmndrs/drei#1179] opened 2022-12-12 14:09 UTC

**Comment by anuragnandi** [comment] 2022-12-12 14:09
`Compiled with problems:X

ERROR in ./node_modules/@react-three/drei/core/Trail.js 104:38-54

export 'MeshLineGeometry' (imported as 'MeshLineGeometry') was not found in 'meshline' (module has no exports)


ERROR in ./node_modules/@react-three/drei/core/Trail.js 107:18-34

export 'MeshLineMaterial' (imported as 'MeshLineMaterial') was not found in 'meshline' (module has no exports)


ERROR in ./node_modules/meshline/dist/index.js 1:0-35

Module not found: Error: Can't resolve './MeshLineGeometry' in 'C:\Users\anura\Desktop\mysite\node_modules\meshline\dist'
Did you mean 'MeshLineGeometry.js'?
BREAKING CHANGE: The request './MeshLineGeometry' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

`

**Comment by krutoo** [comment] 2022-12-12 14:29
same issue

**Comment by aheggie** [comment] 2022-12-13 00:28
identical errors in a project - just trying to import OrbitControls and/or Stats (I tried both individually and same issue) breaks the build with identical errors as above.

I just built and installed it today so maybe its a new issue? I had drei working on a learning project in early October I'm going to try to revert to version number from that project and see if it works.

**Comment by aheggie** [comment] 2022-12-13 00:36
aaaaand fixed

`npm uninstall @react-three/drei`
`npm install @react-three/drei@9.32.4`(9.32.4 is the version from my most recent working app, maybe version in between then and now work also)

worked for me! OrbitControls and Stats both load in fine, no error messages.

**Comment by anuragnandi** [comment] 2022-12-13 00:56
thank you @aheggie 

version 9.32.4 works for me as well

**Comment by Janeshwaran-HexrFactory** [comment] 2022-12-13 06:14
only the recent package (i.e v9.46.4) has this issue, you can uninstall the current version and install v9.46.3

**Comment by Josje92** [comment] 2022-12-13 08:16
Also reported this here:
https://github.com/pmndrs/drei/issues/1177

I'll try downgrading versions to the one @aheggie mentioned an report back how that went.

**Comment by joshuaellis** [comment] 2022-12-13 08:42
duplicate of #1177

**Closed by joshuaellis** 2022-12-13 08:42 UTC
Labels: question
