### ISSUE TITLE
MeshTransmissionMaterial no longer working as of ThreeJS v0.153.0

### ISSUE THREAD

**Issue by rogersanick** [pmndrs/drei#1628] opened 2023-08-24 14:18 UTC
- `three` version: 0.153.0
- `@react-three/drei` version: 9.80.6
- `@react-three/fiber` version: 8.13.7
- `node` version: v18.17.1
- `npm` (or `yarn`) version: 9.6.7

### Problem description:

MeshTransmissionMaterial and MeshPhysicalMaterial both don't work. The scene loads, but the materials don't render and throw an error. 

### Relevant code:

```js
  const config = useMemo(() => ({
    backside: true,
    samples: 10,
    resolution: 1024,
    transmission: 0.5,
    roughness: 0.2,
    thickness: 0.23,
    ior: 1.2,
    chromaticAberration: 0.06,
    anisotropy: 0.52,
    distortion: 0.71,
    distortionScale: 0.33,
    temporalDistortion: 0.2,
    clearcoat: 0.28,
    attenuationDistance: 2.12,
    attenuationColor: '#ffffff',
    color: '#3dc5ff',
    bg: '#1257a3'
  }), []);

      <mesh
        castShadow
        receiveShadow
        geometry={nodes.bumbs.geometry}
        material={materials.cornea}
        position={[0, 0, 0]}
        ref={bodyRef}
      >
        {/* {configurableConfig.meshPhysicalMaterial ? <meshPhysicalMaterial {...configurableConfig} /> : <MeshTransmissionMaterial forceSinglePass={false} background={new THREE.Color(config.bg)} {...configurableConfig} />} */}
        { false ? <MeshTransmissionMaterial forceSinglePass={false} background={new THREE.Color(config.bg)} {...config} /> : <meshPhysicalMaterial {...config} /> }
      </mesh>
```

### Error:

THREE.WebGLProgram: Shader Error 0 - VALIDATE_STATUS false

Program Info Log: Fragment shader is not compiled.
�

FRAGMENT

ERROR: 0:1426: 'vNormalMapUv' : undeclared identifier
ERROR: 0:1426: 'getTangentFrame' : no matching overloaded function found
ERROR: 0:1426: '=' : dimension mismatch
ERROR: 0:1426: '=' : cannot convert from 'const mediump float' to 'highp 3X3 matrix of float'
�

  1421: #endif
  1422: #if defined( USE_NORMALMAP_TANGENTSPACE ) || defined( USE_CLEARCOAT_NORMALMAP ) || defined( USE_ANISOTROPY )
  1423: 	#ifdef USE_TANGENT
  1424: 		mat3 tbn = mat3( normalize( vTangent ), normalize( vBitangent ), normal );
  1425: 	#else
> 1426: 		mat3 tbn = getTangentFrame( - vViewPosition, normal, vNormalMapUv );
  1427: 	#endif
  1428: 	#if defined( DOUBLE_SIDED ) && ! defined( FLAT_SHADED )
  1429: 		tbn[0] *= faceDirection;
  1430: 		tbn[1] *= faceDirection;
  1431: 	#endif
  1432: #endif

**Comment by CodyJasonBennett** [comment] 2023-09-07 06:55
I'm not able to reproduce this. I'd try a clean install in case your version is missing fixes prior to Drei 9.8.

**Comment by rogersanick** [comment] 2023-09-10 23:26
Confirmed this is still happening with a clean install. I even moved to 

    "@react-three/drei": "9.82.1",
    "@react-three/fiber": "8.14.1",

And am still experiencing the same issue.

**Comment by CodyJasonBennett** [comment] 2023-09-13 06:57
Can you share a model or preferably a project link/Codesandbox? I don't think I'm hitting the right code paths from our documented example which presumably doesn't have normals.

**Comment by drcmda** [comment] 2023-09-13 12:43
i used mtm with recent threejs. the issue that you cite was known and imo fixed. maybe you updated package.json but somehow it's using an old drei?

**Comment by vis-prime** [comment] 2023-09-19 14:44
when there's no normal map & anisotropy is greater than 0,  that webgl error comes

https://jsfiddle.net/kwx29aoj/

should get fixed in r157 🤞

**Comment by CodyJasonBennett** [comment] 2023-09-19 14:49
Are you referring to https://github.com/mrdoob/three.js/pull/26716 as for r157? We should backport that here if that's the case.

**Comment by vis-prime** [comment] 2023-09-19 14:54
yup , 

seems to be working

r156 https://jsfiddle.net/pd3j6kqm/1/
r157dev https://jsfiddle.net/9yarh3pt/2/

**Closed** 2023-09-20 12:05 UTC
Labels: bug
