### ISSUE TITLE
Environment component only works on first mount, then stays black

### ISSUE THREAD

**Issue by sbugert** [pmndrs/drei#332] opened 2021-03-21 15:33 UTC
- `three` version: 0.126.1
- `react-three-fiber` version: 5.3.19
- `@react-three/drei` version: 3.11.1
- `node` version: 10.20.1 (CodeSandbox default?)
- `npm` (or `yarn`) version: CodeSandbox

### Problem description:

When using `<Environment />` it seems to only work when mounting a `<Canvas />` for the first time, then it renders a black screen, no errors. My usecase is that I'm mounting it on specific routes, so the client-side routing mounts and unmounts the three component.

### Relevant code:

I made a CodeSandbox reproducing the problem. The official storybook has the same problem when navigating to Environment for the second time.
https://codesandbox.io/s/snowy-cherry-ve9fl?file=/src/index.js

### Suggested solution:

I did some digging and logged some stuff, but couldn't find anything suspicious.

**Comment by susiwen8** [comment] 2021-03-25 15:12
I want to take a look on this.

**Comment by gsimone** [comment] 2021-03-25 18:01
@susiwen8 assigned you the issue, let me know here on discord if you need help

**Comment by susiwen8** [comment] 2021-03-26 01:08
> @susiwen8 assigned you the issue, let me know here on discord if you need help

Thanks

**Comment by drcmda** [comment] 2021-03-26 10:45
i don't think this is a bug in drei/r3f, it's a bug in use-asset.

you are deleting the canvas, which then disposes all data, it it must be black, until here it's expected.

this works: https://codesandbox.io/s/wild-cherry-8cloc?file=/src/index.js

```jsx
<Canvas>
  <OrbitControls />
  <Suspense fallback={null}>
    {show && <Environment background preset="sunset" />}
  </Suspense>
</Canvas>
```

but you should be able to clear the cache:

```jsx
import { useAsset } from 'use-asset'

  ...
  useEffect(() => () => useAsset.clear(), [])
```

and this is where it fails. i know what it is @susiwen8

**Comment by susiwen8** [comment] 2021-03-26 10:48
> i don't think this is a bug in drei/r3f, it's a bug in use-asset.
> 
> you are deleting the canvas, which then disposes all data, it it must be black, until here it's expected.
> 
> this works: https://codesandbox.io/s/wild-cherry-8cloc?file=/src/index.js
> 
> ```js
> <Canvas>
>   <OrbitControls />
>   <Suspense fallback={null}>
>     {show && <Environment background preset="sunset" />}
>   </Suspense>
> </Canvas>
> ```
> 
> but you should be able to clear the cache:
> 
> ```js
> import { useAsset } from 'use-asset'
> 
>   ...
>   useEffect(() => () => useAsset.clear(), [])
> ```
> 
> and this is where it fails. i know what it is @susiwen8

Yes, that's what I suspect, I replace `useAsset` with `useMemo`, it works.

**Comment by drcmda** [comment] 2021-03-26 10:49
> Yes, that's what I suspect, I replace useAsset with useMemo, it works.

that would not be optimal. the reason why its using suspense is because prem gen can take seconds. you will see the scene unlit, and then it will be lit. by adding it to suspense - when the suspense (loading + gen) is done, the suspense is lifted.

**Comment by drcmda** [comment] 2021-03-26 10:55
yep, that was it, it works: https://codesandbox.io/s/nameless-shadow-jhk70

**Comment by susiwen8** [comment] 2021-03-26 11:02
@drcmda I have update `use-asset` to `1.0.4` but `abstractions-environment--environment-st` still have this issue.

**Comment by susiwen8** [comment] 2021-03-26 11:07
> @drcmda I have update `use-asset` to `1.0.4` but `abstractions-environment--environment-st` still have this issue.

I know, it should add `useAsset.clear()` at `useLayoutEffect`.

**Comment by drcmda** [comment] 2021-03-26 11:55
going to copy it in here as well:

imo this can't be something that drei or r3f calls. it will plain delete all cached assets systemwide. textures, modules, images, promises, ... all gone, just because some environment component unmounts.

the issue isn't env unmounting, nothing will happen to the assets, the black screen only came about when he deleted the canvas. but even that shouldn't clear cache because it may contain anything. use-asset and useLoader give the user cache control, it's part of the api. user decides how long cached elements are valid and if they need to be cleared. they don't even need use-asset for that, it's relfected in useLoader as well.

**Comment by joshuaellis** [comment] 2021-03-26 20:31
can someone give me a TLDR so I can 
 a. close the PR some way 
 b. close the issue in some way

thank you 🙏🏼

**Comment by drcmda** [comment] 2021-03-26 21:21
i think its good to close. the bug has been fixed. this imo isn't something that can be controlled by drei as clearing has global and unrelated implications. using cached assets and canvases that mount/unmount imo is an edgecase, the user that wants to do that has to clear the cache manually.

**Closed** 2021-03-26 22:02 UTC
Labels: bug
