### ISSUE TITLE
Why is there no dragcontrols helper ?

### ISSUE THREAD

**Issue by ikteru** [pmndrs/drei#175] opened 2020-10-31 20:08 UTC
You've got all kinds of controls, except for the most important one (kidding) :p . I would love to have one for DragControls as well.

**Comment by drcmda** [comment] 2020-10-31 22:14
make one, add the pr. all these helpers were made as we or someone needed them. :-)

**Comment by gsimone** [comment] 2020-12-26 21:32
Duplicate of #197

**Closed by gsimone** 2020-12-26 21:32 UTC
