### ISSUE TITLE
Html messes with useFrame's mouse values

### ISSUE THREAD

**Issue by mattrossman** [pmndrs/drei#191] opened 2020-12-05 02:32 UTC
See this sandbox:
https://codesandbox.io/s/drei-html-mouse-bug-27qb7?file=/src/App.js

Hovering over the text causes the mouse values to jump down to around -0.9. This can be avoided by styling the component with `pointer-events: none`, but still this seems like incorrect behavior.

**Comment by johnmarinelli** [comment] 2020-12-26 15:05
i tried reproducing this bug locally (see here https://github.com/johnmarinelli/drei/tree/dev/issue-191), but i received the correct mouse coordinates.  here's a gif of what i got: https://gifyu.com/image/Cg5N

**Comment by mattrossman** [comment] 2020-12-26 20:58
Weird, I guess the added layer of Storybook adds some complexity to debugging this. I tried updating the sandbox to the latest drei release but still see the issue.

**Comment by johnmarinelli** [comment] 2020-12-26 21:55
@mattrossman thx, i'll take another look

**Comment by johnmarinelli** [comment] 2021-01-24 21:06
it appears like this is an issue with r3f's `prepareRaycast` function.  there was a commit a while ago that replaced setting the mouse.xy from `clientX, clientY` to `offsetX, offsetY`.  however, when using the Html element, the React.useCallback `event` object is picking up the child <Html> element instead of its parent.  therefore, the offsetXY of the child <Html> element is much smaller than the parent offsetXY, which causes the bug. 

here is the commit: https://github.com/pmndrs/react-three-fiber/pull/782
here is a demonstration that shows the expected behavior, using the provided `raycaster.computeOffsets` option: https://codesandbox.io/s/drei-html-mouse-bug-forked-rmik4?file=/src/App.js

however since it is kind of unrealistic to expect the user to go through this, maybe the provided code in the raycaster.computeOffsets function should be put into the r3f canvas.tsx file?  The provided code should work in all cases - meaning it will solve the problem that axelboc's commit solved, as well as solving this issue.  please let me know what you think @gsimone @joshuaellis

**Comment by joshuaellis** [comment] 2021-01-25 09:13
Thanks @johnmarinelli, I can't imagine this was easy to debug. I think we should move this issue to the r3f repo now, but lets keep the issue open & i'll add a label for `fixed on r3f`. But I personally don't see an issue with your proposal, @drcmda will be more informed on this kind of change than I.

I'll leave with you to open the new issue if that's okay?

**Comment by johnmarinelli** [comment] 2021-04-20 13:39
@mattrossman @joshuaellis the issue seems to be resolved with v6: https://codesandbox.io/s/drei-html-mouse-bug-forked-fixed-0h8i9?file=/src/App.js

**Comment by joshuaellis** [comment] 2021-04-20 14:20
That's awesome to hear. Thanks @johnmarinelli ⭐

**Closed by joshuaellis** 2021-04-20 14:20 UTC
Labels: bug, r3f

**Comment by Solicity-dev** [comment] 2023-01-06 17:16
Hey @joshuaellis! 

The issue seems to be back in the latest versions: 

https://codesandbox.io/s/drei-html-mouse-bug-forked-pg7wqg?file=/src/App.js

And I can't fix it with the following solution that is apparently working on oldest versions: 

https://codesandbox.io/s/drei-html-mouse-bug-forked-rmik4?file=/src/App.js

Any help please?

**Comment by Solicity-dev** [comment] 2023-01-31 17:28
@Marmsilso Hello! Here is the solution I found for my usecase, I don't know if it can help you but here it is: 
(I needed to move an object while moving the mouse)

`function Rig({ canvas, children }) {
    const ref = useRef();

    const [mouse, setMouse] = useState({x:0, y:0});

    useFrame(() => {
        ref.current.position.x = MathUtils.lerp( ref.current.position.x, -(mouse.x * Math.PI), 0.05 )
        ref.current.position.z = MathUtils.lerp( ref.current.position.z, (mouse.y * Math.PI), 0.05 )
    })

    const handleMouseMove = (evt) => {
        const _canvas = canvas.current;

        var rect = _canvas.getBoundingClientRect();

        setMouse({
            x: (evt.clientX / rect.width) * 2 - 1,   
            y: -(evt.clientY / rect.height) * 2 + 1    
        })
    }
    
    useEffect(() => {
        window.addEventListener('mousemove', handleMouseMove);

        return () => {
            window.removeEventListener('mousemove', handleMouseMove);
        }
    }, []);

    return <group ref={ref} onPointerEnter={()=>document.body.style.cursor="grab"} onPointerLeave={()=>document.body.style.cursor="initial"}>{children}</group>
}`

**Comment by Marmsilso** [comment] 2023-02-01 09:50
> @Marmsilso Hello! Here is the solution I found for my usecase, I don't know if it can help you but here it is: (I needed to move an object while moving the mouse)
> 
> `function Rig({ canvas, children }) { const ref = useRef();
> 
> ```
> const [mouse, setMouse] = useState({x:0, y:0});
> 
> useFrame(() => {
>     ref.current.position.x = MathUtils.lerp( ref.current.position.x, -(mouse.x * Math.PI), 0.05 )
>     ref.current.position.z = MathUtils.lerp( ref.current.position.z, (mouse.y * Math.PI), 0.05 )
> })
> 
> const handleMouseMove = (evt) => {
>     const _canvas = canvas.current;
> 
>     var rect = _canvas.getBoundingClientRect();
> 
>     setMouse({
>         x: (evt.clientX / rect.width) * 2 - 1,   
>         y: -(evt.clientY / rect.height) * 2 + 1    
>     })
> }
> 
> useEffect(() => {
>     window.addEventListener('mousemove', handleMouseMove);
> 
>     return () => {
>         window.removeEventListener('mousemove', handleMouseMove);
>     }
> }, []);
> 
> return <group ref={ref} onPointerEnter={()=>document.body.style.cursor="grab"} onPointerLeave={()=>document.body.style.cursor="initial"}>{children}</group>
> ```
> 
> }`
> 
> Where canvas is the ref of the canvas

thank you very much it solved my problem!

**Comment by drcmda** [comment] 2023-02-01 22:26
you don't need to do this
```jsx
<Canvas eventPrefix="client">
```
also
```jsx
<Canvas eventSource={domNode}>
```
if you want to have events on a shared parent

**Comment by timohausmann** [comment] 2023-02-07 15:03
@drcmda I have the same problem, tried both of your suggestions and they alone dont fix the issue. Another eventPrefix makes no difference, passing e.g. a wrapping div to eventSource breaks mouse coordinates.

**Comment by drcmda** [comment] 2023-02-07 23:00
you need t0 put the events on a shared parent and use client coordinates. like this: https://codesandbox.io/s/the-three-graces-0n9it (csb is currently down but check the code)

**Comment by timohausmann** [comment] 2023-02-08 14:34
Thanks alot for the demo! 
I got it working with nextjs, a bit hacky though.
I think my issue comes from SSR and/or routing, where the Canvas is in the global Layout. I get a warning when I use `document.querySelector`, because there is no document on the server and then server and client HTML don't match anymore. If I use a ref, it works initially, but I think `eventSource` is not updated correctly on rerenders, instead the old ref is still used and receives no more events. Now I use this weird kind of reactive ref, which works. 

```js
export function MainCanvas() {

  const [ref, setRef] = useState<HTMLDivElement>();
  const refChanged = useCallback((node: HTMLDivElement) => {
    setRef(node);
  }, []);

  return (
    <div ref= {refChanged}>
    {ref && <Canvas 
      eventSource={ref}
      eventPrefix = "client"
    >
    {props.children}
    </Canvas>}
    </div>
    );
}
```

**Comment by lnxAv** [comment] 2024-08-08 21:36
@timohausmann 
This feels so wrong,
But, I do confirm that it works.
Thank you.
